algoritmo "semnome"
// Função :
// Autor :
// Data : 05/03/2018
// Seção de Declarações 
var
sf,al,em:real
inicio
escreval("Informe o salario do funcionário: ")
leia(sf)
        limpatela

        al<- sf+(sf*0.15)
        em<- al - (al*0.08)
        
escreval("O salario inicial do funcionário é: ",sf)
escreval("O salario do funcionário com o almento de 15% é: ",al)
escreval("O salario final do funcionário com imposto de 8% é: ",em)
// Seção de Comandos 
fimalgoritmo
