algoritmo "semnome"
// Função :
// Autor :
// Data : 01/03/2018
// Seção de Declarações 
var
p,m,g,v:real
inicio

escreval("informe a quantidade de camisetas de tamanho pequeno:")
leia(p)
limpatela

escreval("informe a quantidade de camisetas de tamanho médio:")
leia(m)
limpatela

escreval("informe a quantidade de camisetas de tamanho grande:")
leia(g)
limpatela

v<-(p*10)+(m*12)+(g*15)

escreva("O valor arrecadado é:",v," reais")

fimalgoritmo
