algoritmo "semnome"
// Função :
// Autor :
// Data : 12/03/2018
// Seção de Declarações 
var
n,r1,r2:real
inicio
escreval("Informe um número ai mano: ")
leia(n)




       se n>=0 entao
          r1<-raizq(n)
          escreva("A raiz quadrada desse numero é ",r1:2:2)
          senao
          r2<-n^2
          escreva("O quadrado do número é ",r2)
          fimse
          
// Seção de Comandos 
fimalgoritmo
