algoritmo "semnome"
// Função :
// Autor :
// Data : 12/03/2018
// Seção de Declarações 
var
n1,n2:inteiro
r:real
inicio
escreval("Informe dois numeros inteiros:")
leia(n1)
leia(n2)

      se n1>n2 entao
         r<- n1-n2
         escreva("A diferença entre os numeros é de:",r)
      senao
         r<- n2-n1
         escreva("A diferença entre os numeros é de:",r)
      fimse
// Seção de Comandos 
fimalgoritmo
