algoritmo "semnome"
// Função :
// Autor :
// Data : 12/03/2018
// Seção de Declarações 
var
n1,n2,n3,n4,m:real
inicio
escreval("Informe as quatros notas do aluno: ")
leia(n1)
leia(n2)
leia(n3)
leia(n4)
                  limpatela
        m<- (n1+n2+n3+n4)/4
        
        se m>=6 entao
           escreva("O aluno esta aprovado")
        senao
           escreva("O aluno esta reprovado")
        fimse

// Seção de Comandos 
fimalgoritmo
